#!/bin/bash
# mount rw before executing unison and mount ro afterwards
# # Use like this:
# # unison-gtk -sshcmd /home/user/bin/sshpipe.sh
# intermediate=gateway.cam.ac.uk
SERVER=pi@diderot.servebeer.com
ssh -q $SERVER '/home/pi/bin/mount_rw.sh' 
# echo $@
ssh $@ 
ssh -q $SERVER '/home/pi/bin/mount_ro.sh'
